set encoding=utf-8
set fileencoding=utf-8
set undodir=~/.vimdid
set undofile
set scrolloff=8
set hidden
set nowrap
set signcolumn=yes
set splitright
set splitbelow
set ignorecase
set smartcase
set relativenumber
set number
set shiftwidth=4
set softtabstop=4
set tabstop=4
set guicursor=
set noerrorbells
set expandtab
set smartindent
set noswapfile
set nobackup
set cmdheight=1
set updatetime=50
set shortmess+=c
set colorcolumn=80,120
