local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>S', builtin.find_files, {})
vim.keymap.set('n', '<leader>s', builtin.git_files, {})
vim.keymap.set('n', '<leader>f', function() 
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
